name: CI-CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  # ============================================================
  # CI
  # Build da imagem Docker e Push para o OCI Container Registry
  # ============================================================
  CI:
    name: CI - Build e Push
    runs-on: ubuntu-latest

    steps:

      # ----------------------------------------------------------
      # Checkout
      # ----------------------------------------------------------
      - name: Obtendo o código
        uses: actions/checkout@v4


      # ----------------------------------------------------------
      # Login no OCI Container Registry
      # ----------------------------------------------------------
      - name: Login to OCIR
        uses: docker/login-action@v3
        with:
          registry: gru.ocir.io
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_TOKEN }}


      # ----------------------------------------------------------
      # Build e Push da imagem
      # ----------------------------------------------------------
      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true

          tags: |
            gru.ocir.io/grglog7bpvjm/primeira-pipeline-cicd:v${{ github.run_number }}
            gru.ocir.io/grglog7bpvjm/primeira-pipeline-cicd:latest


  # ============================================================
  # CD
  # Deploy no Oracle Kubernetes Engine - OKE
  # ============================================================
  CD:
    name: CD - Deploy OKE
    runs-on: ubuntu-latest

    needs:
      - CI

    steps:

      # ----------------------------------------------------------
      # Checkout
      # ----------------------------------------------------------
      - name: Obtendo o código
        uses: actions/checkout@v4


      # ==========================================================
      # OCI CLI
      # ==========================================================

      - name: Instalar OCI CLI
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install oci-cli


      # ----------------------------------------------------------
      # Verificar OCI CLI
      # ----------------------------------------------------------
      - name: Verificar OCI CLI
        run: |
          echo "PATH=$PATH"

          which oci

          oci --version
          
      # ==========================================================
      # Kubernetes
      # ==========================================================

      # ----------------------------------------------------------
      # Configurar kubeconfig
      # ----------------------------------------------------------
      - name: Configuração de contexto do Kubernetes
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      # ----------------------------------------------------------
      # Aplicar Deployment
      # ----------------------------------------------------------
      - name: Aplicar Manifesto
        run: |
          kubectl apply \
            -f ./k8s/deployment.yaml