name: CI-CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  # ============================================================
  # CI
  # Build da imagem Docker e Push para o OCI Container Registry
  # ============================================================
  CI:
    name: CI - Build e Push
    runs-on: ubuntu-latest

    steps:

      # ----------------------------------------------------------
      # Checkout
      # ----------------------------------------------------------
      - name: Obtendo o código
        uses: actions/checkout@v4


      # ----------------------------------------------------------
      # Login no OCI Container Registry
      # ----------------------------------------------------------
      - name: Login to OCIR
        uses: docker/login-action@v3
        with:
          registry: gru.ocir.io
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_TOKEN }}


      # ----------------------------------------------------------
      # Build e Push da imagem
      # ----------------------------------------------------------
      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true

          tags: |
            gru.ocir.io/grglog7bpvjm/primeira-pipeline-cicd:v${{ github.run_number }}
            gru.ocir.io/grglog7bpvjm/primeira-pipeline-cicd:latest
  CD:
    needs: [CI]
    uses: wesleymlopes/primeira-pipeline-cicd/.github/workflows/deploy.yaml@main
    with:
      manifests: k8s/deployment.yaml
      images: gru.ocir.io/grglog7bpvjm/primeira-pipeline-cicd:v${{ github.run_number }}
    secrets: inherit
